services:
  app:
    build:
      context: ./php
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./tests:/var/www/tests
      - ./vendor:/var/www/vendor
      - ./composer.json:/var/www/composer.json
      - ./phpunit.xml:/var/www/phpunit.xml
      - ./.env:/var/www/.env

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: suziria
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
