services:
  app:
    build:
      context: ./php
    container_name: suziria_test
    volumes:
      - ./public:/var/www/html             
      - ./src:/var/www/src                   
      - ./vendor:/var/www/vendor             
      - ./composer.json:/var/www/composer.json  
      - ./composer.lock:/var/www/composer.lock 
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: suziria_db
    restart: always
    environment:
      POSTGRES_DB: suziria
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
